# Generated by Django 5.2.17 on 2026-08-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=50)),
                ("source", models.CharField(max_length=50)),
                ("duration_seconds", models.IntegerField(default=0)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="meetings/audio/"
                    ),
                ),
                ("transcription_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
